### ISSUE TITLE
Device status update issue

### ISSUE THREAD

**Issue by daserra23** [jgaalen/domoticz-apc-ups-plugin#3]
I use the method in the closed "issue" to trigger dzvents scripts, however the "APC-Status" device is updated even when it's value hasn't changed so the script is constantly triggered every time the plugin checks (reading interval).

It would be nice if the device only gets updated if the value has changed which would stop my script running unnecessarily. Similar to "checkFirst" in dzvents but in the plugin.

**Comment by jgaalen** [comment]
Ok i’ll look into it soon

**Comment by jgaalen** [comment]
Fixed, values only update when they are changed

**Comment by daserra23** [comment]
Tested and working perfectly.
